/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* T_fk:(i0[9])->(o0[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][5] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=arg[0]? arg[0][7] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a2=sin(a2);
  a8=(a1*a2);
  a9=arg[0]? arg[0][6] : 0;
  a10=sin(a9);
  a11=(a8*a10);
  a0=sin(a0);
  a9=cos(a9);
  a12=(a0*a9);
  a11=(a11+a12);
  a5=sin(a5);
  a12=(a11*a5);
  a7=(a7-a12);
  a12=arg[0]? arg[0][8] : 0;
  a13=cos(a12);
  a14=(a7*a13);
  a15=(a4*a5);
  a11=(a11*a6);
  a15=(a15+a11);
  a12=sin(a12);
  a11=(a15*a12);
  a14=(a14-a11);
  if (res[0]!=0) res[0][0]=a14;
  a14=arg[0]? arg[0][3] : 0;
  a11=sin(a14);
  a16=(a11*a0);
  a17=(a16*a3);
  a14=cos(a14);
  a18=(a14*a2);
  a17=(a17+a18);
  a18=(a17*a6);
  a19=(a14*a3);
  a16=(a16*a2);
  a19=(a19-a16);
  a16=(a19*a10);
  a20=(a11*a1);
  a21=(a20*a9);
  a16=(a16+a21);
  a21=(a16*a5);
  a18=(a18+a21);
  a21=(a18*a13);
  a22=(a17*a5);
  a16=(a16*a6);
  a22=(a22-a16);
  a16=(a22*a12);
  a21=(a21-a16);
  if (res[0]!=0) res[0][1]=a21;
  a21=(a11*a2);
  a16=(a14*a0);
  a23=(a16*a3);
  a21=(a21-a23);
  a23=(a21*a6);
  a14=(a14*a1);
  a1=(a14*a9);
  a16=(a16*a2);
  a11=(a11*a3);
  a16=(a16+a11);
  a11=(a16*a10);
  a1=(a1-a11);
  a11=(a1*a5);
  a23=(a23-a11);
  a11=(a23*a13);
  a5=(a21*a5);
  a1=(a1*a6);
  a5=(a5+a1);
  a1=(a5*a12);
  a11=(a11-a1);
  if (res[0]!=0) res[0][2]=a11;
  a11=0.;
  if (res[0]!=0) res[0][3]=a11;
  a0=(a0*a10);
  a1=(a8*a9);
  a0=(a0-a1);
  if (res[0]!=0) res[0][4]=a0;
  a1=(a19*a9);
  a20=(a20*a10);
  a1=(a1-a20);
  if (res[0]!=0) res[0][5]=a1;
  a9=(a16*a9);
  a14=(a14*a10);
  a9=(a9+a14);
  if (res[0]!=0) res[0][6]=a9;
  if (res[0]!=0) res[0][7]=a11;
  a7=(a7*a12);
  a14=(a15*a13);
  a7=(a7+a14);
  if (res[0]!=0) res[0][8]=a7;
  a18=(a18*a12);
  a14=(a22*a13);
  a18=(a18+a14);
  if (res[0]!=0) res[0][9]=a18;
  a23=(a23*a12);
  a13=(a5*a13);
  a23=(a23+a13);
  if (res[0]!=0) res[0][10]=a23;
  if (res[0]!=0) res[0][11]=a11;
  a11=-2.0000000000000001e-001;
  a7=(a11*a7);
  a15=(a11*a15);
  a13=-8.5050000000000001e-002;
  a0=(a13*a0);
  a12=1.8300000000000000e-001;
  a4=(a12*a4);
  a14=-4.7000000000000000e-002;
  a8=(a14*a8);
  a4=(a4-a8);
  a8=arg[0]? arg[0][0] : 0;
  a4=(a4+a8);
  a0=(a0+a4);
  a15=(a15+a0);
  a7=(a7+a15);
  if (res[0]!=0) res[0][12]=a7;
  a18=(a11*a18);
  a22=(a11*a22);
  a1=(a13*a1);
  a17=(a12*a17);
  a19=(a14*a19);
  a17=(a17+a19);
  a19=arg[0]? arg[0][1] : 0;
  a17=(a17+a19);
  a1=(a1+a17);
  a22=(a22+a1);
  a18=(a18+a22);
  if (res[0]!=0) res[0][13]=a18;
  a23=(a11*a23);
  a11=(a11*a5);
  a13=(a13*a9);
  a12=(a12*a21);
  a14=(a14*a16);
  a12=(a12+a14);
  a14=arg[0]? arg[0][2] : 0;
  a12=(a12+a14);
  a13=(a13+a12);
  a11=(a11+a13);
  a23=(a23+a11);
  if (res[0]!=0) res[0][14]=a23;
  a23=1.;
  if (res[0]!=0) res[0][15]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int T_fk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int T_fk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int T_fk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void T_fk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int T_fk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void T_fk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void T_fk_incref(void) {
}

CASADI_SYMBOL_EXPORT void T_fk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int T_fk_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int T_fk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real T_fk_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* T_fk_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* T_fk_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* T_fk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* T_fk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int T_fk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
